apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  labels:
    app: rabbitmq
type: Opaque
stringData:
  # Use stringData for plain text (K8s will auto-encode to base64)
  RABBITMQ_DEFAULT_PASS: "guest"

